### ISSUE TITLE
Relationship between PIMLibrary and PIMMock

### ISSUE THREAD

**Issue by yongwonshin** [SAITPublic/OneMCC#1]
Hi,

PIMMock is intended to be a drop-in replacement for PIMLibrary. However, when I install PIMMock and try to build PimAiCompiler, the header file (pim_data_types.h) is incompatible (e.g., `PimBo`) and missing necessary types (e.g., `PimActFunc`) with PimAiCompiler.

Is PIMMock not yet fully stabilized for PimAiCompiler?

**Comment by Hyessun** [comment]
PIMMock is intended to be a host-device in SYCL. It emulates backend that is executed as native C++ code and emulates the SYCL execution and memory model. It also can be used to execute kernels without backend drivers and for debugging purposes.
